const mongoose = require("mongoose");
const { Content, Note, Article, YoutubeLink } = require("../models/ContentModel");
const {
  geminiSubmoduleArticleFetcher,
  geminiSubmoduleVideoFetcher,
} = require("../geminiAPI/geminiSubmoduleContentFetcher");
const {
  youtubeLinksDummy,
  articlesDummy,
} = require("../dummyData/dummyContent");

const withTransaction = require("../utils/withTransaction");

// POST : Generate videos from gemini ? / Dummy Data
const generateArticles = withTransaction(async (req, res, session) => {
  const { contentId, skillName, moduleName, submoduleName, useAI } = req.body;

  // Get content doc
  const contentDoc = await Content.findById(contentId).session(session);
  if (!contentDoc) {
    console.log("Article Generation Failed: Parent Content not found");
    return res.status(404).json({
      message: "Article generation failed: Parent Content not found.",
    });
  }

  // Authenticate user
  if (contentDoc.userId.toString() !== req.user._id.toString()) {
    console.log("Article Generation Failed: Unauthorized user");
    return res.status(401).json({
      message: "Cannot generate articles: Unauthorized user.",
    });
  }

  // Fetch articles
  const fetchedArticles = useAI
    ? await geminiSubmoduleArticleFetcher(skillName, moduleName, submoduleName)
    : articlesDummy;

  if (!fetchedArticles || fetchedArticles.length === 0) {
    return res
      .status(200)
      .json({ message: "No articles generated by AI", data: [] });
  }

  // Save articles
  const articleDocs = await Article.insertMany(
    fetchedArticles.map((article) => ({
      title: article.title,
      link: article.link,
      summary: article.summary,
    })),
    { session }
  );

  // Link to content
  contentDoc.articles.push(...articleDocs.map((a) => a._id));
  await contentDoc.save({ session });

  return res.status(200).json({
    message: "Article generation successful",
    data: articleDocs,
  });
});

// POST : Generate videos from gemini ? / Dummy Data
const generateVideos = withTransaction(async (req, res, session) => {
  const { contentId, skillName, moduleName, submoduleName, useAI } = req.body;

  // Get content doc
  const contentDoc = await Content.findById(contentId).session(session);
  if (!contentDoc) {
    console.log("Video Generation Failed: Parent Content not found");
    return res.status(404).json({
      message: "Video generation failed: Parent Content not found.",
    });
  }

  // Authenticate user
  if (contentDoc.userId.toString() !== req.user._id.toString()) {
    console.log("Video Generation Failed: Unauthorized user");
    return res.status(401).json({
      message: "Cannot generate videos: Unauthorized user.",
    });
  }

  // Fetch videos
  const fetchedVideos = useAI
    ? await geminiSubmoduleVideoFetcher(skillName, moduleName, submoduleName)
    : youtubeLinksDummy;

  if (!fetchedVideos || fetchedVideos.length === 0) {
    return res.status(200).json({ message: "No videos generated", data: [] });
  }

  // Save each fetched video as a YoutubeLink document
  const videoDocs = await YoutubeLink.insertMany(
    fetchedVideos.map((video) => ({
      title: video.title,
      link: video.link,
      userId: req.user._id,
    })),
    { session }
  );

  // Add their IDs to the content document
  contentDoc.youtubeLinks.push(...videoDocs.map((v) => v._id));
  await contentDoc.save({ session });

  // Return the saved documents in the response
  return res.status(200).json({
    message: "Video generation successful",
    data: videoDocs,
  });
});

const getContentArticles = async (req, res) => {
  try {
    const contentId = req.params.contentId;

    const contentDoc = await Content.findById(contentId);
    if (!contentDoc) {
      return res.status(404).json({
        message: "Content with given Id not found",
      });
    }

    if (contentDoc.userId.toString() !== req.user._id.toString()) {
      return res.status(401).json({
        message: "Unauthorized user",
      });
    }

    await contentDoc.populate("articles");
    const contentArticles = contentDoc.articles;
    console.log("Sent Articles : ", contentArticles);
    return res.status(200).json(contentArticles);
  } catch (error) {
    console.error(error);
    return res.status(500).json({
      message: "Failed to fetch content articles",
    });
  }
};

const getContentVideos = async (req, res) => {
  try {
    const contentId = req.params.contentId;

    const contentDoc = await Content.findById(contentId);
    if (!contentDoc) {
      return res.status(404).json({
        message: "Content with given Id not found",
      });
    }

    if (contentDoc.userId.toString() !== req.user._id.toString()) {
      return res.status(401).json({
        message: "Unauthorized user",
      });
    }

    await contentDoc.populate("youtubeLinks");
    const contentVideos = contentDoc.youtubeLinks;
    console.log("Sent Videos : ", contentVideos);
    return res.status(200).json(contentVideos);
  } catch (error) {
    console.error(error);
    return res.status(500).json({
      message: "Failed to fetch content videos",
    });
  }
};

module.exports = { generateArticles, generateVideos, getContentArticles, getContentVideos };
