const roadmap = [
    {
      title: "Introduction to Machine Learning",
      status: "Pending",
      submodules: [
        { title: "What is Machine Learning?", type: "Learning", status: "Completed" },
        { title: "Types of Machine Learning", type: "Learning", status: "Completed" },
        { title: "Real-world Applications", type: "Learning", status: "Pending" },
        { title: "Supervised vs Unsupervised Learning", type: "Learning", status: "Completed" },
        { title: "Model Training Basics", type: "Learning", status: "Pending" },
        { title: "Overfitting and Underfitting", type: "Learning", status: "Pending" },
        { title: "Bias-Variance Tradeoff", type: "Learning", status: "Pending" },
        { title: "ML Workflow Overview", type: "Learning", status: "Completed" },
      ],
    },
    {
      title: "Python for ML",
      status: "Pending",
      submodules: [
        { title: "Python Basics", type: "Learning", status: "Completed" },
        { title: "Using Jupyter Notebooks", type: "Practice", status: "Completed" },
        { title: "Numpy Essentials", type: "Learning", status: "Completed" },
        { title: "Pandas for Data Analysis", type: "Learning", status: "Completed" },
        { title: "Data Cleaning Project", type: "Project", status: "Pending" },
        { title: "Matplotlib and Seaborn", type: "Learning", status: "Pending" },
        { title: "Scikit-learn Overview", type: "Learning", status: "Pending" },
        { title: "Practice Data Loading & Exploration", type: "Practice", status: "Pending" },
      ],
    },
    {
      title: "Data Preprocessing",
      status: "Pending",
      submodules: [
        { title: "Handling Missing Values", type: "Learning", status: "Completed" },
        { title: "Encoding Categorical Variables", type: "Learning", status: "Completed" },
        { title: "Feature Scaling Techniques", type: "Learning", status: "Completed" },
        { title: "Outlier Detection", type: "Learning", status: "Pending" },
        { title: "Text Data Preprocessing", type: "Learning", status: "Pending" },
        { title: "Image Data Preprocessing", type: "Learning", status: "Pending" },
        { title: "Data Preprocessing Practice", type: "Practice", status: "Pending" },
        { title: "Mini Preprocessing Project", type: "Project", status: "Pending" },
      ],
    },
    {
      title: "Supervised Learning",
      status: "Pending",
      submodules: [
        { title: "Linear Regression", type: "Learning", status: "Completed" },
        { title: "Logistic Regression", type: "Learning", status: "Completed" },
        { title: "K-Nearest Neighbors (KNN)", type: "Learning", status: "Pending" },
        { title: "Decision Trees", type: "Learning", status: "Pending" },
        { title: "Random Forests", type: "Learning", status: "Pending" },
        { title: "SVMs", type: "Learning", status: "Pending" },
        { title: "Classification Metrics", type: "Learning", status: "Completed" },
        { title: "Supervised Learning Practice", type: "Practice", status: "Pending" },
        { title: "Predict Housing Prices (Project)", type: "Project", status: "Pending" },
      ],
    },
    {
      title: "Unsupervised Learning",
      status: "Pending",
      submodules: [
        { title: "K-Means Clustering", type: "Learning", status: "Completed" },
        { title: "Hierarchical Clustering", type: "Learning", status: "Pending" },
        { title: "DBSCAN", type: "Learning", status: "Pending" },
        { title: "Dimensionality Reduction", type: "Learning", status: "Completed" },
        { title: "PCA", type: "Learning", status: "Completed" },
        { title: "Anomaly Detection", type: "Learning", status: "Pending" },
        { title: "Customer Segmentation Project", type: "Project", status: "Pending" },
        { title: "Unsupervised Learning Practice", type: "Practice", status: "Pending" },
      ],
    },
    {
      title: "Model Deployment",
      status: "Pending",
      submodules: [
        { title: "Pickle & Joblib for Model Saving", type: "Learning", status: "Completed" },
        { title: "Deploy with Flask", type: "Learning", status: "Completed" },
        { title: "FastAPI for Deployment", type: "Learning", status: "Pending" },
        { title: "Create ML REST API", type: "Practice", status: "Pending" },
        { title: "Dockerize ML App", type: "Learning", status: "Pending" },
        { title: "Deploy to Render/Heroku", type: "Practice", status: "Pending" },
        { title: "ML Deployment Project", type: "Project", status: "Pending" },
        { title: "Model Monitoring Basics", type: "Learning", status: "Pending" },
        { title: "CI/CD for ML Apps", type: "Learning", status: "Pending" },
      ],
    },
  ]

module.exports = roadmap;